// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZToU7PKKsTbH6YcDLqDlZkwNvIL0oMHY',
    appId: '1:915399947091:web:38cd5a56200e8bd9d767a6',
    messagingSenderId: '915399947091',
    projectId: 'tawfeer-market-2ae89',
    authDomain: 'tawfeer-market-2ae89.firebaseapp.com',
    storageBucket: 'tawfeer-market-2ae89.firebasestorage.app',
    measurementId: 'G-EQFJKJY4L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqEkW-6gWWDWtpL6RhLaOo0qnDYPsgnLs',
    appId: '1:915399947091:android:c3654b845a675641d767a6',
    messagingSenderId: '915399947091',
    projectId: 'tawfeer-market-2ae89',
    storageBucket: 'tawfeer-market-2ae89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIEo51ZRMJC47TETqHcmN9SfPIH_4Xd8E',
    appId: '1:915399947091:ios:6af723d5da310146d767a6',
    messagingSenderId: '915399947091',
    projectId: 'tawfeer-market-2ae89',
    storageBucket: 'tawfeer-market-2ae89.firebasestorage.app',
    iosBundleId: 'com.example.tawfeerMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIEo51ZRMJC47TETqHcmN9SfPIH_4Xd8E',
    appId: '1:915399947091:ios:6af723d5da310146d767a6',
    messagingSenderId: '915399947091',
    projectId: 'tawfeer-market-2ae89',
    storageBucket: 'tawfeer-market-2ae89.firebasestorage.app',
    iosBundleId: 'com.example.tawfeerMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZToU7PKKsTbH6YcDLqDlZkwNvIL0oMHY',
    appId: '1:915399947091:web:ba7fdc284b3e58b3d767a6',
    messagingSenderId: '915399947091',
    projectId: 'tawfeer-market-2ae89',
    authDomain: 'tawfeer-market-2ae89.firebaseapp.com',
    storageBucket: 'tawfeer-market-2ae89.firebasestorage.app',
    measurementId: 'G-8TQQ2RXBH7',
  );
}
